apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-pod
  template:
    metadata:
      labels:
        app: kubectl-pod
    spec:
      containers:
        - name: kubectl-container
          image: kubectl:0.1
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.1"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "512Mi"